### ISSUE TITLE
Tutorial key name mismatch

### ISSUE THREAD

**Issue by justinfaulkner** [clearlyTHUYDOAN/mux-direct-upload#1]
Hello!

I ran into an issue when I was following the tutorial at https://www.mux.com/blog/direct-uploads-with-mux-upload-button

I followed the tutorial closely, but when I tried to upload a file, the post request from my node server to `/video/v1/uploads` was failing with a `401 Unauthorized` response.

I checked the API Key code and noticed the code in the repo doesn't seem to work properly with the tutorial. (Or maybe I missed something)

The blog tutorial has the reader put these values in `.env`:

```
MUX_ACCESS_TOKEN_ID=[your mux access token id]
MUX_SECRET_KEY=[your mux secret key]
```

But `server.js` expects different keys:

```
  auth: {
    username: process.env.API_USERNAME,
    password: process.env.API_KEY,
  },
```

Some possible solutions, not sure which is best:
1. Update `server.js` to match the tutorial
    - MUX_ACCESS_TOKEN_ID
    - MUX_SECRET_KEY
2. Update tutorial to match `server.js`
    -  API_USERNAME
    - API_KEY
3. Update both to `server.js` and the tutorial to use the keys from the "Download as .env file" button on https://dashboard.mux.com/
    - MUX_TOKEN_ID
    - MUX_TOKEN_SECRET
   
I can open a PR for option 1 if that helps.

Regardless, thanks for the tutorial and repo!

**Comment by clearlyTHUYDOAN** [comment]
Hey Justin, thanks for submitting this issue!

You might have already gotten my first response via email. But I quickly figured out what went wrong.

Thanks for providing your experience plus some options. I'm gonna go with option 1. Look out for the fix shortly!

**Comment by justinfaulkner** [comment]
Thanks Thuy! That works great!

I made a clean checkout of the latest, and re-followed the tutorial, and everything worked! Thanks for the quick response and fix!
